### ISSUE TITLE
Front End: Employer Landing Page

### ISSUE THREAD

**Issue by Sarthak-Oza** [tlg-23-08-sde-3/23-08-JavaScriptProject-Team1-FrontEnd#4]

**Comment by Sarthak-Oza** [comment]
# Subtasks

- [ ] Form to create a new job
- [ ] View all jobs created and details
- [ ] Search candidates who applied for the job
